(setq blink-cursor-mode nil)
(setq column-number-mode t)
(menu-bar-mode -1)
(setq minibuffer-eldef-shorten-default t)
(setq scroll-bar-mode t)
(setq show-paren-mode t)
(setq show-paren-style 'mixed)
(setq tool-bar-mode nil)
